import { useEffect, useState } from "react";
import type { Project } from "../types";
import { dummyGenerations } from "../assets/assets";
import { Loader2Icon, Sparkles } from "lucide-react";
import ProjectCard from "../components/ProjectCard";
import { motion } from "framer-motion";

const Community = () => {
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchProjects = async () => {
    // Simulating API call
    setTimeout(() => {
      setProjects(dummyGenerations);
      setLoading(false);
    }, 1500);
  };

  useEffect(() => {
    fetchProjects();
  }, []);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen gap-6 bg-black">
        <div className="relative">
          <Loader2Icon className="size-10 animate-spin text-violet-500" />
          <div className="absolute inset-0 blur-2xl bg-violet-600/30 rounded-full animate-pulse" />
        </div>
        <p className="text-gray-400 font-bold uppercase tracking-[0.2em] text-xs animate-pulse">
          Browsing the collective...
        </p>
      </div>
    );
  }

  return (
    <div className="min-h-screen text-white bg-black">
      {/* Decorative backdrop elements */}
      <div className="fixed top-0 left-1/4 w-[500px] h-[500px] bg-violet-600/10 blur-[150px] -z-10 animate-pulse" />
      <div className="fixed bottom-0 right-1/4 w-[300px] h-[300px] bg-indigo-600/10 blur-[120px] -z-10" />

      <div className="max-w-7xl mx-auto px-6 pt-32 pb-40">
        <header className="mb-24 relative">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: "easeOut" }}
            className="flex flex-col items-center text-center"
          >
            <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-violet-500/10 border border-violet-500/20 text-violet-400 mb-6">
              <Sparkles className="size-4" />
              <span className="text-[10px] font-black uppercase tracking-[0.2em]">Live Feed</span>
            </div>

            <h1 className="text-5xl md:text-7xl font-black mb-8 tracking-tighter bg-gradient-to-b from-white via-white to-white/20 bg-clip-text text-transparent">
              Community <br className="md:hidden" /> Creations
            </h1>

            <p className="text-gray-400 max-w-2xl text-lg leading-relaxed font-medium">
              Explore the frontiers of AI-driven brand imagery. A curated gallery of <span className="text-white">stunning visuals</span> generated by our creator community.
            </p>
          </motion.div>
        </header>

        {/* Masonry Layout */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1, delay: 0.3 }}
          className="columns-1 sm:columns-2 lg:columns-3 xl:columns-4 gap-6 space-y-6"
        >
          {projects.map((project) => (
            <ProjectCard
              key={project.id}
              gen={project}
              setGenerations={setProjects}
              forCommunity={true}
            />
          ))}
        </motion.div>

        {projects.length === 0 && (
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="flex flex-col items-center justify-center py-40 border border-dashed border-white/10 rounded-[3rem] bg-white/[0.02] backdrop-blur-sm"
          >
            <div className="w-20 h-20 rounded-full bg-white/5 flex items-center justify-center mb-6">
              <Sparkles className="size-10 text-gray-700" />
            </div>
            <p className="text-gray-500 font-bold uppercase tracking-widest text-sm">The gallery is currently quiet.</p>
            <p className="text-gray-600 mt-2">Check back soon for new inspirations.</p>
          </motion.div>
        )}
      </div>
    </div>
  );
};

export default Community;